# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'currencyConvertor' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for currencyConvertor
	pod 'CurrencyRequest', '~> 0.1'
  target 'currencyConvertorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'currencyConvertorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
